src/app/[...slug]/page.tsx
src/components/ConfigComponent.tsx
src/components/ContentSections.tsx
src/components/SideMenu.tsx
src/constants/cardsConfig.ts
src/constants/exploreFolders.ts
src/constants/navigation.ts
src/lib/authAndFetch.ts
src/lib/helpers.ts

this PR will fix the bug noted in https://app.dework.xyz/zechub-2424/main-space-20666/view/board-leodduex?taskId=8f0a8778-117f-43a3-a6b5-fe160d702093

fix: reformat internal linking

---

public/notification-content/data.json
public/notification-data/data.json
src/app/actions.ts
src/app/admin/banner-notification/page.tsx
src/app/page.tsx
src/components/AccountDisplay/AccountDisplay.tsx
src/components/Admin/AdminComp.css
src/components/Admin/AdminComp.tsx
src/components/AppProvider.tsx
src/components/Notification/NotificationBanner.tsx
src/components/Notification/NotificationBannerForm/NotificationBannerForm.tsx
src/lib/helpers.ts

Speedfox/dw 194/add toastify notificatio

---

package.json
src/app/page.tsx
src/components/ContentSections.tsx
src/components/home/Home.tsx
src/components/ui/Cards.tsx
src/components/ui/FadeInAnimation.tsx
yarn.lock

closes https://github.com/ZecHub/zechub/issues/667

feat: landing page fade-in animations

---

src/app/dashboard/page.tsx

closes https://github.com/ZecHub/zechub/issues/680
https://app.dework.xyz/?taskId=5691c68e-ada6-4799-ba8d-6a5580f32b5a

feat: dashboard page

---

src/app/dao/page.tsx
src/components/Navigation.tsx
src/components/home/Home.tsx
src/components/ui/MemberCards.tsx
src/constants/navigation.ts

Created a new DAO page as zechub.wiki/dao moved DAO information to dao page.

 Create a dao page

---

src/app/layout.tsx
src/components/Hero.tsx
src/components/Navigation.tsx
src/components/Notification/NotificationBanner.tsx
src/components/explorer/Explorer.tsx
src/components/home/Home.tsx
src/components/ui/Logo.tsx
src/lib/helpers.ts

Made a fix for the content banners

Content Banners

---

.eslintrc.json
package.json
prettier.json
src/app/dao/page.tsx
src/app/layout.tsx
src/components/Footer.tsx
src/components/Navigation.tsx
src/components/SearchBar/SearchInput.tsx
src/components/SearchBar/index.tsx
src/components/ui/MemberCards.tsx
src/components/ui/Sheet.tsx
src/constants/membersDao.ts
src/types.d.ts
yarn.lock

Fixing some styles and code formatting
Fix url for "DAO" and "Dashboard" buttons.... the old implementations doesn't work properly if you're not in the homepage

fixing some styles and code

---

src/app/donation/page.tsx
src/components/Donation/Donation.tsx
src/components/Navigation.tsx
src/components/ui/DonationBtn.tsx

Change Donation page from Javascript to Typescript, check before merge

change donation page from js to tsx

---

src/app/desktop-wallets/page.tsx
src/app/globals.css
src/app/hardware-wallets/page.tsx
src/app/mobile-wallets/page.tsx
src/app/using-zcash/Wallets/[...slug]/page.tsx
src/app/web-wallets/page.tsx
src/components/MdxComponentWallet.tsx
src/components/SideMenu.tsx
src/components/rehype-wrap-sections.tsx
src/constants/walletsConfig.ts

Create Cards for Wallets Section

---

src/app/[...slug]/page.tsx
src/app/desktop-wallets/page.tsx
src/app/globals.css
src/app/hardware-wallets/page.tsx
src/app/layout.tsx
src/app/mobile-wallets/page.tsx
src/app/web-wallets/page.tsx
src/components/Footer.tsx
src/components/Navigation.tsx
src/components/SideMenu.tsx
src/components/ui/DonationBtn.tsx
src/constants/navigation.ts

Correct Website Formatting

---

src/components/Navigation.tsx

Fix mobile nav in dark mode

---

src/app/desktop-wallets/page.tsx
src/app/hardware-wallets/page.tsx
src/app/mobile-wallets/page.tsx
src/app/web-wallets/page.tsx

Website Design Improvements

---

src/components/SideMenu.tsx

button text "Explore more" -> "Explore"

---

src/app/[...slug]/page.tsx
src/app/globals.css
src/app/using-zcash/shielded-pools/page.tsx
src/components/SideMenu.tsx
src/constants/navigation.ts

Pool Banners / YT Icon / Podcast page

---

src/components/ContentSections.tsx
src/components/DEXListing/DEXListing.tsx
src/components/DEXListing/DexListing.css
src/components/DEXListing/index.tsx
src/constants/dex-listing.ts

Added new Cards component which matches with current design

feat: add DEXListing card

---

src/app/dashboard/page.tsx
src/components/Button/Button.module.css
src/components/Button/Button.tsx
src/components/FilterToggle.tsx
src/components/HalvingMeter/halving-meter.css
src/components/HalvingMeter/halving-meter.tsx
src/components/WalletItem.tsx

Made some little fixes to some lint error from other components as well as brush up to the Dashboard page components

Speedfox/dw 292/add halving meter zech

---

src/app/dao/page.tsx

better look to links

---

src/app/[...slug]/page.tsx
src/app/dao/page.tsx
src/app/dashboard/page.tsx
src/app/desktop-wallets/page.tsx
src/app/donation/page.tsx
src/app/explore/page.tsx
src/app/hardware-wallets/page.tsx
src/app/mobile-wallets/page.tsx
src/app/using-zcash/blockchain-explorers/page.tsx
src/app/using-zcash/non-custodial-exchanges/page.tsx
src/app/using-zcash/shielded-pools/page.tsx
src/app/wallets/page.tsx
src/app/web-wallets/page.tsx
src/lib/helpers.ts
yarn.lock

This feature will add URL previews along with other optional page metadata to enhance the richness of shared links.

add URL previews

---

package-lock.json
package.json
src/components/WalletItem.tsx
src/pages/api/wallet-likes.js
yarn.lock

If it doesn't work, you'll need to install the pg package:
``` 
npm install pg 
```
and don't forget to add this variable in **.env.local** (if it's not already added, which it might be)
``` 
POSTGRES_URL="postgresql://username:password@host:port/database" 
```

Added wallet likes in postgres

---

src/app/wallets/page.tsx
src/components/WalletList.tsx

made wallet filter mobile friendly

---

src/components/WalletList.tsx
src/pages/api/wallet-likes.js

If you want to change the daily limit, go to `**pages/api/wallet-likes.js**' and increase this variable:
```
const dailyLimit4WalletVotes = 5;
```

added daily limits for wallet likes

---

src/app/educational/page.tsx
src/components/Educational/Educational.tsx
src/constants/educational.ts
yarn.lock

This Pull Request has the basic for the app, please check to made the proper corrections and future additions
go to zechub.wiki/educational to check

educational app

---

src/app/[...slug]/page.tsx
src/constants/searcher.ts
src/lib/helpers.ts

Contribute page fixed and added new word for search bar for the hackathon

fixing contributing page

---

src/app/zcash-projects/page.tsx
src/components/Grid/Grid.module.css
src/components/Grid/Grid.tsx
src/components/ProjectCards/ProjectCards.module.css
src/components/ProjectCards/ProjectCards.tsx
src/components/ZcashProjects/ZcashProjects.tsx
src/components/ZcashProjects/zcashProjects.css

Created new url path "/zcash-projects" and its content.

New ProjectCard, New Zcash-Project, New Grid

---

src/components/Penumbra/PenumbraWalletConnect.tsx

This PR adds some formatting to the balance of UM

update: refactor balance item

---

src/app/sitemap/page.tsx
src/components/SiteLinks/SiteLinks.module.css
src/components/SiteLinks/SiteLinks.tsx
src/components/Sitemap/Sitemap.tsx
src/components/Sitemap/sitemap.css

Sitemap url route added

---

next.config.js
src/components/TransactionSummaryChart.tsx

This PR adds timeframes filter to the chart

Speedfox/dw 547/chart timeframes zechu

---

src/app/[...slug]/page.tsx

FIxed slug type mismatch error

FIxed slug type mismatch error

---

src/components/Grid/Grid.tsx

The rhipper patch 1 :1st_place_medal: Project Tachyon

---

src/app/globals.css
src/app/layout.tsx
src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/dropdown.css
src/components/DropdownMobile/DropdownMobile.tsx
src/components/DropdownMobile/dropdown.mobile.css
src/components/Navigation/Navigation.tsx
src/components/SearchBar/index.tsx
src/components/UI/AnimationHome.tsx
src/components/UI/Sheet.tsx
tailwind.config.ts

Navbar for mobile and desktop view fixed

Navbar for mobile and desktop view fixed

---

package-lock.json
src/app/using-zcash/centralizedswaps/page.tsx
src/app/using-zcash/custodial-exchanges/page.tsx
src/components/SiteLinks/SiteLinks.tsx
src/constants/navigation.ts
src/constants/searcher.ts

Centralized swaps url name updated

Centralized swaps url name updated

---

src/app/developers/quick-start/page.tsx
src/components/Footer/Footer.tsx
src/components/TabsPage/TabsPage.tsx

Added zaino and Zingo CLI tabs

Added zaino and Zingo CLI

---

src/app/developers/quick-start/page.tsx
src/components/TabsPage/TabsPage.tsx

Zaino and Zingo CLI key prop fix

Zaino and Zingo CLI key prop fix

---

src/app/dex/page.tsx
src/constants/decentralizedExchanges.ts
yarn.lock

Created dex url and dex page

---

src/app/omniflix/page.tsx
src/components/VideoCard/VideoCard.module.css
src/components/VideoCard/VideoCard.tsx
src/constants/navigation.ts
src/constants/omniflixMedia.ts

Added omniflix media page and ZKAV to organizations

Added omniflix media page and ZKAV to organizations

---

src/app/omniflix/page.tsx

Fixed omniflix bugs

---

src/components/DAO/index.tsx

Added button for 'Governance How To'

Added button for 'Governance How To'

---

src/components/Charts/Zcash/NetInflowsOutflowsChart.tsx
yarn.lock

FIxed Net Sapling Flow display

FIxed Net Sapling Flow display

---

public/js/zechub-widget.js
src/app/embed/zcash/page.tsx

Widget for zechub charts added at zechub-widget.js

Widget for zechub charts added at zechub-widget.js

---

src/components/Sitemap/Sitemap.tsx
src/components/Sitemap/sitemap.css
src/constants/siteLinks.ts

Revamped sitemap url route and added the new url routes

Revamped sitemap url route and added the new url routes
